services:
  - type: web
    name: royal-palace-hotel-api
    env: node
    plan: free
    buildCommand: cd apps/backend && npm install && npx prisma generate && npx prisma db push --accept-data-loss
    startCommand: cd apps/backend && npm start
    healthCheckPath: /health
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: royalpalace-db
          property: connectionString
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: FRONTEND_URL
        value: https://rishavdevtiwari.com.np
      - key: HOTEL_EMAIL
        value: rishavdevtiwari01@gmail.com
      - key: EMAIL_PASSWORD
        sync: false
    domains:
      - api.rishavdevtiwari.com.np

databases:
  - name: royalpalace-db
    plan: free  # 
    databaseName: royalpalace_db
 

