services:
  # Backend API Service (Free Plan)
  - type: web
    name: royal-palace-hotel-api
    env: node
    plan: free  # ✅ Using free plan
    buildCommand: cd apps/backend && npm install && npx prisma generate && npx prisma db push --accept-data-loss
    startCommand: cd apps/backend && npm start
    healthCheckPath: /health
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: royalpalace-db
          property: connectionString
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: FRONTEND_URL
        value: https://rishavdevtiwari.com.np
      - key: HOTEL_EMAIL
        value: rishavdevtiwari01@gmail.com
      - key: EMAIL_PASSWORD
        sync: false
    domains:
      - api.rishavdevtiwari.com.np

databases:
  - name: royalpalace-db
    plan: free  # ✅ Using free plan
    databaseName: royalpalace_db

  # Frontend Service (Static Site with Free Plan)
  # - type: static  
  #   name: royal-palace-hotel
  #   env: static
  #   buildCommand: cd apps/frontend && npm install && npm run build
  #   staticPublishPath: apps/frontend/dist
  #   headers:
  #     - path: /*
  #       name: Cache-Control
  #       value: no-cache
  #   envVars:
  #     - key: NODE_ENV
  #       value: production
  #   domains:
  #     - rishavdevtiwari.com.np
  #     - www.rishavdevtiwari.com.np
  #   autoDeploy: true  

